"""
Event types for the event-driven backtesting engine.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class EventType(Enum):
    MARKET = "MARKET"
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    FILL = "FILL"


class Direction(Enum):
    LONG = 1
    SHORT = -1
    EXIT = 0


@dataclass
class MarketEvent:
    """Triggered on each new bar of market data."""
    type: EventType = field(default=EventType.MARKET, init=False)
    timestamp: datetime = datetime.now()
    ticker: str = ""
    open: float = 0.0
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    volume: int = 0


@dataclass
class SignalEvent:
    """Generated by a strategy when it detects a trading opportunity."""
    type: EventType = field(default=EventType.SIGNAL, init=False)
    ticker: str = ""
    direction: Direction = Direction.LONG
    strength: float = 1.0
    timestamp: datetime = datetime.now()


@dataclass
class OrderEvent:
    """Represents an order to be sent to the execution handler."""
    type: EventType = field(default=EventType.ORDER, init=False)
    ticker: str = ""
    direction: Direction = Direction.LONG
    quantity: int = 0
    order_type: str = "MARKET"
    limit_price: float = 0.0
    timestamp: datetime = datetime.now()

    def __repr__(self) -> str:
        return (
            f"Order({self.direction.name} {self.quantity} {self.ticker} "
            f"@ {self.order_type})"
        )


@dataclass
class FillEvent:
    """Returned by the execution handler after an order is filled."""
    type: EventType = field(default=EventType.FILL, init=False)
    ticker: str = ""
    direction: Direction = Direction.LONG
    quantity: int = 0
    fill_price: float = 0.0
    commission: float = 0.0
    slippage: float = 0.0
    timestamp: datetime = datetime.now()

    @property
    def total_cost(self) -> float:
        return self.commission + self.slippage

    def __repr__(self) -> str:
        return (
            f"Fill({self.direction.name} {self.quantity} {self.ticker} "
            f"@ {self.fill_price:.2f}, cost={self.total_cost:.2f})"
        )
